version: '3'
services:
  # database container
  db:
      image: postgres:latest
      environment:
          POSTGRES_USER: evething
          POSTGRES_PASSWORD: evething
      # Expose for debugging/remote connection
      ports:
          - "5432:5432"
  # redis container
  redis:
      image: redis:latest
      # Expose redis port
      ports:
          - "6379:6379"
  # container with Django dev server
  django:
      build:
        context: .
        dockerfile: docker/Dockerfile-dev
      image: evething_django:latest
      user: evething
      #command: bash -c ". /evething-env/bin/activate && /evething/manage.py runserver 0.0.0.0:8000"
      command: bash -c ". /evething-env/bin/activate && /evething/manage.py runserver django:8000"
      volumes:
          - .:/evething  # mount current directory inside container
      ports:
          - "8000:8000"
      links:
          - db:db
          - redis:redis
      environment:
          - PYTHONUNBUFFERED=1
  # container with celery worker
  celery:
      build:
        context: .
        dockerfile: docker/Dockerfile-dev
      image: evething_django:latest
      user: evething
      command: bash -c ". /evething-env/bin/activate && celery worker -A evething -B -Q et_high,et_medium,et_low -c 2"
      volumes:
          - .:/evething
      links:
          - db:db
          - redis:redis
      environment:
          - PYTHONUNBUFFERED=1

volumes:
  .:

